#### L1 Norms

In [17]:
from numpy import array
from numpy.linalg import norm
from numpy import inf

In [18]:
a = array([4, 5, 5])
print(a)
L1 = norm(a,1)
print(L1)

[4 5 5]
14.0


#### L2 Norm

In [19]:
a = array([1, 2, 3])
print(a)
L1 = norm(a,2)
print(L1)

[1 2 3]
3.7416573867739413


#### Max Norm

In [21]:
a = array([1, 2, 7])
print(a)
L1 = norm(a,inf)
print(L1)

[1 2 7]
7.0
